package org.openymsg.network;

/**
 * 
 * This class represents and instant message (IM) which is sent or received on the Yahoo network
 * 
 * @author Mehran Maghoumi, aka SirM2X (maghoumi@gmail.com)
 */
public class IM
{
	/**
	 * The unique number string for this message generated by Session.java
	 */
	private String messageNumberString;
	
	/**
	 * The sender of this message
	 */
	private String from;
	
	/**
	 * The recipient of this message
	 */
	private String to;
	
	/**
	 * The contents of this message
	 */
	private String message;
	
	
	/**
	 * Creates a new IM based on the information provided as the parameters
	 * @param messageNumberString
	 * 		The unique number string for this message.
	 * @param from
	 * 		The sender of this message.
	 * @param to
	 * 		The recipient of this message.
	 * @param message
	 * 		The contents of this message
	 */
	public IM(String messageNumberString, String from, String to, String message)
	{
		this.messageNumberString = messageNumberString;
		this.from = from;
		this.to = to;
		this.message = message;
	}
	
	/**
	 * Returns the unique number string of this message
	 * @return The unique number string of this message
	 */
	public String getMessageNumberString()
	{
		return messageNumberString;
	}
	
	/**
	 * Sets the unique message number string
	 * @param messageNumberString
	 * 			The string to be used as the unique message number string of this message
	 */
	public void setMessageNumberString(String messageNumberString)
	{
		this.messageNumberString = messageNumberString;
	}
	
	/**
	 * Returns the sender of this message 
	 * @return The sender of this message
	 */
	public String getFrom()
	{
		return from;
	}
	
	/**
	 * Sets the sender of this message
	 * @param from
	 * 		The sender's ID
	 */
	public void setFrom(String from)
	{
		this.from = from;
	}
	
	/**
	 * Returns the recipient of this message
	 * @return	The recipient of this message
	 */
	public String getTo()
	{
		return to;
	}
	
	/**
	 * Sets the recipient of this message
	 * @param to
	 * 		The ID of the message recipient
	 */
	public void setTo(String to)
	{
		this.to = to;
	}
	
	/**
	 * Returns the contents of this message
	 * @return The contents of this message
	 */
	public String getMessage()
	{
		return message;
	}
	
	/**
	 * Sets the contents of this message
	 * @param message
	 * 		A string representing the contents of this message
	 */
	public void setMessage(String message)
	{
		this.message = message;
	}
	
	@Override
	public String toString()
	{
		return "[From]: " + from + " [To]: " + to + " [Number]: " + messageNumberString + " [Message]: " + message;
	}
}
